name: deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install serverless CLI
        run: npm install -g serverless@3.38.0

      - name: install serverless plugins
        run: |
          npm install --save-dev serverless-python-requirements
          npm install --save-dev serverless-step-functions

      - name: Ensure Docker is running
        uses: addnab/docker-run-action@v3
        with:
          image: hello-world

      # Ya no es necesario instalar dependencias Python manualmente, serverless las empaqueta usando Docker
      # - name: install Python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.USER_SERVERLESS_PYTHON }}
          aws-secret-access-key: ${{ secrets.USER_SERVERLESS_PYTHON_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: deploy with serverless
        run: serverless deploy
        env:
          API_GOOGLE: ${{ secrets.API_GOOGLE }}

